#!/usr/sbin/nft -f
flush ruleset

table inet fw {
  chain input {
    type filter hook input priority 0; policy accept;
  }
  chain forward {
    type filter hook forward priority 0; policy drop;
  }
  chain output {
    type filter hook output priority 0; policy drop;
    oif "lo" accept
    ct state established,related accept
    ip daddr 169.254.169.254 drop
    ip6 daddr fd00:ec2::254 drop
    udp dport 53 accept
    tcp dport 53 accept
    udp dport 123 accept
    icmp type echo-request accept
  }
}

table ip nat {
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    iif "lo" return
    tcp dport { 61022, 80, 443, 8000 } return
    tcp dport 1-65535 redirect to :8000
  }
}
