#!/bin/sh
# Generate etc/nginx-hostmap.conf from etc/names.env. Run from the repo root.
#
# nginx cannot read an env file, and rollup.py cannot read an nginx map, so the
# one source feeds both: this generates the map, rollup parses names.env directly.
set -e
ENV_FILE="${1:-etc/names.env}"
OUT="${2:-etc/nginx-hostmap.conf}"
. "$ENV_FILE"

esc() { printf '%s' "$1" | sed 's/\./\\./g'; }
addr_dashed=$(printf '%s' "$HOST_ADDR" | tr '.' '-')

# Every regex is quoted: nginx treats { and } as block delimiters, so an
# unquoted ~^\d{1,3} is a syntax error, not a regex.
{
  echo "# Generated by ops/gen-hostmap.sh from $ENV_FILE. Do not edit."
  echo "map \$http_host \$hp_host_class {"
  echo "    default                                        foreign;"
  echo "    \"\"                                             derived;"
  for n in $BAIT_NAMES;    do printf '    "~*^%s(:\\d+)?$"  bait;\n'    "$(esc "$n")"; done
  for n in $CONTROL_NAMES; do printf '    "~*^%s(:\\d+)?$"  control;\n' "$(esc "$n")"; done
  echo "    \"~^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}(:\\d+)?\$\"  derived;"
  echo "    \"~^\\[[0-9a-fA-F:.]+\\](:\\d+)?\$\"  derived;"
  printf '    "~%s\\."  derived;\n' "$addr_dashed"
  echo "}"
} > "$OUT"
echo "wrote $OUT"
